'@extends':
    '@parent'

form:
  fields:
    system_tabs:
      fields:
        content:
          fields:
            pages.process:
              type: checkboxes
              default: [markdown: false, zmarkdown: true, twig: false]
              options:
                markdown: Markdown
                zmarkdown: zmarkdown
                twig: Twig
              use: keys
